# Generated by Django 4.2.4 on 2023-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=3000, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=3000, verbose_name='last_name')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('role', models.CharField(choices=[('', 'Abonné'), ('', 'créateur'), ('', 'Administrateur')], default='', max_length=50, verbose_name='role')),
            ],
        ),
    ]
