# Generated by Django 4.2.4 on 2023-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=3000),
        ),
    ]
