# Generated by Django 4.2.4 on 2023-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titled', models.CharField(max_length=3000)),
                ('potos', models.ImageField(upload_to='images/')),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
