# Generated by Django 4.2.4 on 2023-11-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='potos',
            new_name='photos',
        ),
    ]
