# Generated by Django 4.2.4 on 2023-11-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_image', '0002_rename_potos_post_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photos',
            new_name='photo',
        ),
    ]
